#!/usr/bin/env bash
set -euo pipefail

readonly DEFAULT_MAX_COUNT=20
readonly MAX_ALLOWED_COUNT=50
readonly MIN_ORACLE_MINOR=18

usage() {
  printf 'Usage: %s [MAX_COUNT]\n' "${0##*/}"
  printf '  MAX_COUNT must be an integer from 1 through %d (default: %d).\n' \
    "$MAX_ALLOWED_COUNT" "$DEFAULT_MAX_COUNT"
}

if (( $# > 1 )); then
  usage >&2
  exit 2
fi

max_count="${1:-$DEFAULT_MAX_COUNT}"
if [[ ! "$max_count" =~ ^[0-9]+$ ]]; then
  printf 'error: MAX_COUNT must be an integer from 1 through %d\n' "$MAX_ALLOWED_COUNT" >&2
  exit 2
fi
max_count=$((10#$max_count))
if (( max_count < 1 || max_count > MAX_ALLOWED_COUNT )); then
  printf 'error: MAX_COUNT must be an integer from 1 through %d\n' "$MAX_ALLOWED_COUNT" >&2
  exit 2
fi

for command_name in oracle gh jq; do
  if ! command -v "$command_name" >/dev/null 2>&1; then
    printf 'error: %s is not available in PATH\n' "$command_name" >&2
    exit 1
  fi
done

if ! gh auth status >/dev/null 2>&1; then
  printf 'error: gh is not authenticated\n' >&2
  exit 1
fi
owner_login="$(gh api user --jq .login)"
if [[ ! "$owner_login" =~ ^[A-Za-z0-9-]+$ ]]; then
  printf 'error: invalid authenticated GitHub login: %s\n' "$owner_login" >&2
  exit 1
fi

if ! oracle_version_output="$(oracle --version 2>&1)"; then
  printf '%s\n' "$oracle_version_output" >&2
  exit 1
fi
if [[ ! "$oracle_version_output" =~ ([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
  printf 'error: could not parse Oracle version from: %s\n' "$oracle_version_output" >&2
  exit 1
fi
oracle_major="${BASH_REMATCH[1]}"
oracle_minor="${BASH_REMATCH[2]}"
if (( oracle_major == 0 && oracle_minor < MIN_ORACLE_MINOR )); then
  printf 'error: Oracle 0.%d.0 or newer is required; found %s\n' \
    "$MIN_ORACLE_MINOR" "$oracle_version_output" >&2
  exit 1
fi

oracle bridge doctor >&2

out_file="$(mktemp)"
err_file="$(mktemp)"
cleanup() {
  rm -f -- "$out_file" "$err_file"
}
trap cleanup EXIT

run_sweep() {
  oracle \
    --wait \
    --heartbeat 15 \
    --engine browser \
    --model gpt-5.6-sol \
    --browser-thinking-time extra-high \
    -p - >"$out_file" 2>"$err_file" <<EOF
# Account PR sweep
@GitHub Review open, non-draft pull requests in non-archived repositories whose owner login is exactly $owner_login. Order eligible PRs by most recently updated first and review at most $max_count. Do not include organization-owned or collaborator repositories.

Review the selected PRs as one batch. For each PR, inspect the current diff and enough repository context to evaluate correctness, regressions, maintainability, security implications, and dependency/update risk. Inspect CI/check status, existing reviews, and unresolved review feedback when available. Apply KISS, DRY, and YAGNI to concrete maintainability issues and avoid style-only findings.

Bind each result to the exact PR head SHA you reviewed. Before finalizing, re-read every reviewed PR head. Mark a PR current only when that final re-read still matches the reviewed SHA; if it changed, mark it stale. Mark a PR blocked when required review context is unavailable.

Classify actionable findings as blocking, should-fix, or optional. Do not invent findings. For current, non-blocked PRs, prepare one non-empty COMMENT review body. Put actionable findings into inline_comments whenever they can be safely anchored to changed lines in the reviewed diff; keep findings that cannot be safely line-anchored in review_body. If there are no actionable findings, say so in review_body. Do not include the Generated by ChatGPT footer; the caller adds it during publication.

Do not modify repositories, pull requests, reviews, comments, threads, labels, checks, branches, commits, or any other GitHub state. The caller publishes reviews through an authenticated write-capable gh client after validating this result.

Return exactly one JSON object and no Markdown fence or surrounding prose. Use this schema:
{"owner_login":"LOGIN","effective_limit":NUMBER,"eligible_count":NUMBER_OR_NULL,"omitted_count":NUMBER_OR_NULL,"reviews":[{"repository":"OWNER/REPO","number":NUMBER,"title":"TITLE","head_sha":"40_HEX_SHA","state":"current|stale|blocked","review_body":"NONEMPTY_FOR_CURRENT_NONBLOCKED","inline_comments":[{"path":"REPO_RELATIVE_PATH","line":NUMBER,"side":"LEFT|RIGHT","body":"COMMENT"}],"reason":"REASON_OR_EMPTY"}],"report":"CONSOLIDATED_MARKDOWN_REPORT_WITHOUT_PUBLICATION_CLAIMS"}

EOF
}

retry_delays=(1 2 4 8 16 30 30 30 30 30)
retry_index=0

while :; do
  : >"$out_file"
  : >"$err_file"

  if run_sweep; then
    if [[ -s "$err_file" ]]; then
      cat -- "$err_file" >&2
    fi

    if ! jq -e \
      --arg owner "$owner_login" \
      --argjson limit "$max_count" \
      '
        type == "object"
        and .owner_login == $owner
        and .effective_limit == $limit
        and (.reviews | type == "array")
        and (.report | type == "string")
        and all(
          .reviews[];
          (.repository | type == "string")
          and (.number | type == "number" and . > 0 and floor == .)
          and (.title | type == "string")
          and (.head_sha | type == "string" and test("^[0-9A-Fa-f]{40}$"))
          and (.state == "current" or .state == "stale" or .state == "blocked")
          and (.review_body | type == "string")
          and (.inline_comments | type == "array")
          and all(
            .inline_comments[];
            (.path | type == "string" and length > 0)
            and (.line | type == "number" and . > 0 and floor == .)
            and (.side == "LEFT" or .side == "RIGHT")
            and (.body | type == "string" and length > 0)
          )
          and (
            .state != "current"
            or (
              (.review_body | length > 0)
              and (.review_body | contains("Generated by ChatGPT") | not)
            )
          )
        )
      ' "$out_file" >/dev/null; then
      printf 'error: Oracle returned an invalid sweep result\n' >&2
      cat -- "$out_file" >&2
      exit 1
    fi

    printf '%s\n' "$(jq -r '.report' "$out_file")"
    published_count=0
    stale_count=0
    failed_count=0

    while IFS= read -r review; do
      state="$(jq -r '.state' <<<"$review")"
      [[ "$state" == "current" ]] || continue

      repository="$(jq -r '.repository' <<<"$review")"
      number="$(jq -r '.number' <<<"$review")"
      reviewed_sha="$(jq -r '.head_sha' <<<"$review")"

      if [[ ! "$repository" =~ ^"$owner_login"/[A-Za-z0-9._-]+$ ]]; then
        printf '[PUBLICATION FAILED] %s#%s: invalid repository identity\n' "$repository" "$number" >&2
        ((failed_count += 1))
        continue
      fi

      if ! current_sha="$(gh api "repos/$repository/pulls/$number" --jq .head.sha)"; then
        printf '[PUBLICATION FAILED] %s#%s: could not re-read current head\n' "$repository" "$number" >&2
        ((failed_count += 1))
        continue
      fi
      if [[ "$current_sha" != "$reviewed_sha" ]]; then
        printf '[STALE] %s#%s: reviewed %s, current %s; review not published\n' \
          "$repository" "$number" "$reviewed_sha" "$current_sha" >&2
        ((stale_count += 1))
        continue
      fi

      payload="$(
        jq -c '
          {
            commit_id: .head_sha,
            event: "COMMENT",
            body: (.review_body + "\n\n---\nGenerated by ChatGPT"),
            comments: [.inline_comments[] | {path, line, side, body}]
          }
        ' <<<"$review"
      )"
      if gh api \
        --method POST \
        "repos/$repository/pulls/$number/reviews" \
        --input - <<<"$payload" >/dev/null; then
        printf '[PUBLISHED] %s#%s @ %s\n' "$repository" "$number" "$reviewed_sha"
        ((published_count += 1))
      else
        printf '[PUBLICATION FAILED] %s#%s @ %s\n' "$repository" "$number" "$reviewed_sha" >&2
        ((failed_count += 1))
      fi
    done < <(jq -c '.reviews[]' "$out_file")

    printf 'Publication summary: published=%d stale=%d failed=%d\n' \
      "$published_count" "$stale_count" "$failed_count"
    (( failed_count == 0 )) || exit 1
    exit 0
  else
    exit_code=$?
  fi

  last_stderr="$(awk 'NF { line = $0 } END { print line }' "$err_file")"
  last_stdout_error="$(awk '/^ERROR:/ { line = $0 } END { print line }' "$out_file")"

  if [[ "$last_stderr" == "✖ read ETIMEDOUT" || "$last_stdout_error" == "ERROR: read ETIMEDOUT" ]]; then
    cat -- "$out_file"
    cat -- "$err_file" >&2
    exit "$exit_code"
  fi

  if [[ "$last_stderr" == "✖ busy" || "$last_stdout_error" == "ERROR: busy" ]]; then
    if (( retry_index < ${#retry_delays[@]} )); then
      sleep "${retry_delays[$retry_index]}"
      ((retry_index += 1))
      continue
    fi
  fi

  cat -- "$out_file"
  cat -- "$err_file" >&2
  exit "$exit_code"
done
