#!/usr/bin/env bash
#
# Review the authenticated user's open pull requests with Oracle + ChatGPT.
#
# Usage:
#   oracle-pr-sweep.sh [--debug] [--dry-run] [--max-count=<int>]
#   oracle-pr-sweep.sh [MAX_COUNT]
#   oracle-pr-sweep.sh -h|--help
#
# Options:
#   --debug             Enable shell tracing
#   --dry-run           Generate and validate reviews without publishing them
#   --max-count=<int>   Review at most this many PRs (default: 20, range: 1-50)
#   -h, --help          Print this help text and exit
#
# Arguments:
#   MAX_COUNT           Backward-compatible positional form of --max-count

set -euo pipefail

if (( $# > 0 )); then
  for arg in "$@"; do
    [[ "$arg" == '--debug' ]] && set -x && break
  done
fi

readonly COMMAND_NAME="${0##*/}"
readonly DEFAULT_MAX_COUNT=20
readonly MAX_ALLOWED_COUNT=50
readonly MIN_ORACLE_MINOR=18
readonly CHATGPT_FOOTER='Generated by ChatGPT'
readonly -a RETRY_DELAYS=(1 2 4 8 16 30 30 30 30 30)

max_count="$DEFAULT_MAX_COUNT"
max_count_set=0
dry_run=0
out_file=''
err_file=''
owner_login=''

print_usage() {
  sed -ne '1,2d; /^#/!q; s/^#$/# /; s/^# //p' "${BASH_SOURCE[0]}"
}

abort() {
  printf '%s: %s\n' "$COMMAND_NAME" "$*" >&2
  exit 1
}

usage_error() {
  printf '%s: %s\n\n' "$COMMAND_NAME" "$*" >&2
  print_usage >&2
  exit 2
}

set_max_count() {
  (( max_count_set == 0 )) || usage_error 'MAX_COUNT may be specified only once'
  max_count="$1"
  max_count_set=1
}

parse_args() {
  while (( $# > 0 )); do
    case "$1" in
      --debug)
        shift
        ;;
      --dry-run)
        dry_run=1
        shift
        ;;
      --max-count)
        (( $# >= 2 )) || usage_error 'option --max-count requires an argument'
        set_max_count "$2"
        shift 2
        ;;
      --max-count=*)
        set_max_count "${1#*=}"
        shift
        ;;
      -h|--help)
        print_usage
        exit 0
        ;;
      --)
        shift
        while (( $# > 0 )); do
          set_max_count "$1"
          shift
        done
        ;;
      -*)
        usage_error "invalid option: $1"
        ;;
      *)
        set_max_count "$1"
        shift
        ;;
    esac
  done
}

validate_max_count() {
  [[ "$max_count" =~ ^[0-9]+$ ]] \
    || usage_error "MAX_COUNT must be an integer from 1 through $MAX_ALLOWED_COUNT"
  max_count=$((10#$max_count))
  (( max_count >= 1 && max_count <= MAX_ALLOWED_COUNT )) \
    || usage_error "MAX_COUNT must be an integer from 1 through $MAX_ALLOWED_COUNT"
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || abort "$1 is not available in PATH"
}

check_prerequisites() {
  local command_name oracle_major oracle_minor oracle_version_output

  for command_name in oracle gh jq; do
    require_command "$command_name"
  done

  gh auth status >/dev/null 2>&1 || abort 'gh is not authenticated'
  owner_login="$(gh api user --jq .login)"
  [[ "$owner_login" =~ ^[A-Za-z0-9-]+$ ]] \
    || abort "invalid authenticated GitHub login: $owner_login"

  if ! oracle_version_output="$(oracle --version 2>&1)"; then
    printf '%s\n' "$oracle_version_output" >&2
    exit 1
  fi
  [[ "$oracle_version_output" =~ ([0-9]+)\.([0-9]+)\.([0-9]+) ]] \
    || abort "could not parse Oracle version from: $oracle_version_output"
  oracle_major="${BASH_REMATCH[1]}"
  oracle_minor="${BASH_REMATCH[2]}"
  if (( oracle_major == 0 && oracle_minor < MIN_ORACLE_MINOR )); then
    abort "Oracle 0.$MIN_ORACLE_MINOR.0 or newer is required; found $oracle_version_output"
  fi

  oracle bridge doctor >&2
}

create_temp_files() {
  out_file="$(mktemp)"
  err_file="$(mktemp)"
}

cleanup() {
  [[ -z "$out_file" ]] || rm -f -- "$out_file"
  [[ -z "$err_file" ]] || rm -f -- "$err_file"
}

run_sweep() {
  oracle \
    --wait \
    --heartbeat 15 \
    --engine browser \
    --model gpt-5.6-sol \
    --browser-thinking-time extra-high \
    -p - >"$out_file" 2>"$err_file" <<EOF_PROMPT
# Account PR sweep
@GitHub Review open, non-draft pull requests in non-archived repositories whose owner login is exactly $owner_login. Order eligible PRs by most recently updated first and review at most $max_count. Do not include organization-owned or collaborator repositories.

Review the selected PRs as one batch. For each PR, inspect the current diff and enough repository context to evaluate correctness, regressions, maintainability, security implications, and dependency/update risk. Inspect CI/check status, existing reviews, and unresolved review feedback when available. Apply KISS, DRY, and YAGNI to concrete maintainability issues and avoid style-only findings.

Bind each result to the exact PR head SHA you reviewed. Before finalizing, re-read every reviewed PR head. Mark a PR current only when that final re-read still matches the reviewed SHA; if it changed, mark it stale. Mark a PR blocked when required review context is unavailable.

Classify actionable findings as blocking, should-fix, or optional. Do not invent findings. For current, non-blocked PRs, prepare one non-empty COMMENT review body. Put actionable findings into inline_comments whenever they can be safely anchored to changed lines in the reviewed diff; keep findings that cannot be safely line-anchored in review_body. If there are no actionable findings, say so in review_body. Do not include the Generated by ChatGPT footer; the caller adds it during publication.

Do not modify repositories, pull requests, reviews, comments, threads, labels, checks, branches, commits, or any other GitHub state. The caller publishes reviews through an authenticated write-capable gh client after validating this result.

Return exactly one JSON object and no Markdown fence or surrounding prose. Use this schema:
{"owner_login":"LOGIN","effective_limit":NUMBER,"eligible_count":NUMBER_OR_NULL,"omitted_count":NUMBER_OR_NULL,"reviews":[{"repository":"OWNER/REPO","number":NUMBER,"title":"TITLE","head_sha":"40_HEX_SHA","state":"current|stale|blocked","review_body":"NONEMPTY_FOR_CURRENT_NONBLOCKED","inline_comments":[{"path":"REPO_RELATIVE_PATH","line":NUMBER,"side":"LEFT|RIGHT","body":"COMMENT"}],"reason":"REASON_OR_EMPTY"}],"report":"CONSOLIDATED_MARKDOWN_REPORT_WITHOUT_PUBLICATION_CLAIMS"}
EOF_PROMPT
}

validate_sweep_result() {
  jq -e \
    --arg owner "$owner_login" \
    --argjson limit "$max_count" \
    --arg footer "$CHATGPT_FOOTER" \
    '
      type == "object"
      and .owner_login == $owner
      and .effective_limit == $limit
      and ((.eligible_count == null) or (.eligible_count | type == "number" and . >= 0 and floor == .))
      and ((.omitted_count == null) or (.omitted_count | type == "number" and . >= 0 and floor == .))
      and (.reviews | type == "array" and length <= $limit)
      and (([.reviews[] | [.repository, .number]] | unique | length) == (.reviews | length))
      and (.report | type == "string")
      and all(
        .reviews[];
        (.repository | type == "string")
        and (.number | type == "number" and . > 0 and floor == .)
        and (.title | type == "string")
        and (.head_sha | type == "string" and test("^[0-9A-Fa-f]{40}$"))
        and (.state == "current" or .state == "stale" or .state == "blocked")
        and (.review_body | type == "string")
        and (.inline_comments | type == "array")
        and (.reason | type == "string")
        and all(
          .inline_comments[];
          (.path | type == "string" and length > 0)
          and (.line | type == "number" and . > 0 and floor == .)
          and (.side == "LEFT" or .side == "RIGHT")
          and (.body | type == "string" and length > 0)
        )
        and (
          .state != "current"
          or (
            (.review_body | length > 0)
            and (.review_body | contains($footer) | not)
          )
        )
      )
    ' "$out_file" >/dev/null
}

process_reviews() {
  local current_sha failed_count=0 number payload published_count=0 repository review
  local reviewed_sha stale_count=0 state validated_count=0
  local failure_label='PUBLICATION FAILED'

  (( dry_run == 0 )) || failure_label='VALIDATION FAILED'

  while IFS= read -r review; do
    state="$(jq -r '.state' <<<"$review")"
    [[ "$state" == 'current' ]] || continue

    repository="$(jq -r '.repository' <<<"$review")"
    number="$(jq -r '.number' <<<"$review")"
    reviewed_sha="$(jq -r '.head_sha' <<<"$review")"

    if [[ ! "$repository" =~ ^[A-Za-z0-9-]+/[A-Za-z0-9._-]+$ \
      || "${repository%%/*}" != "$owner_login" ]]; then
      printf '[%s] %s#%s: invalid repository identity\n' \
        "$failure_label" "$repository" "$number" >&2
      ((failed_count += 1))
      continue
    fi

    if ! current_sha="$(gh api "repos/$repository/pulls/$number" --jq .head.sha)"; then
      printf '[%s] %s#%s: could not re-read current head\n' \
        "$failure_label" "$repository" "$number" >&2
      ((failed_count += 1))
      continue
    fi
    if [[ "$current_sha" != "$reviewed_sha" ]]; then
      printf '[STALE] %s#%s: reviewed %s, current %s; review not published\n' \
        "$repository" "$number" "$reviewed_sha" "$current_sha" >&2
      ((stale_count += 1))
      continue
    fi

    payload="$(
      jq -c --arg footer "$CHATGPT_FOOTER" '
        {
          commit_id: .head_sha,
          event: "COMMENT",
          body: (.review_body + "\\n\\n---\\n" + $footer),
          comments: [.inline_comments[] | {path, line, side, body}]
        }
      ' <<<"$review"
    )"

    if (( dry_run )); then
      printf '[VALIDATED] %s#%s @ %s\n' "$repository" "$number" "$reviewed_sha"
      ((validated_count += 1))
      continue
    fi

    if gh api \
      --method POST \
      "repos/$repository/pulls/$number/reviews" \
      --input - <<<"$payload" >/dev/null; then
      printf '[PUBLISHED] %s#%s @ %s\n' "$repository" "$number" "$reviewed_sha"
      ((published_count += 1))
    else
      printf '[PUBLICATION FAILED] %s#%s @ %s\n' "$repository" "$number" "$reviewed_sha" >&2
      ((failed_count += 1))
    fi
  done < <(jq -c '.reviews[]' "$out_file")

  if (( dry_run )); then
    printf 'Dry-run summary: validated=%d stale=%d failed=%d\n' \
      "$validated_count" "$stale_count" "$failed_count"
  else
    printf 'Publication summary: published=%d stale=%d failed=%d\n' \
      "$published_count" "$stale_count" "$failed_count"
  fi
  (( failed_count == 0 ))
}
run_with_retries() {
  local exit_code last_stderr last_stdout_error retry_index=0

  while :; do
    : >"$out_file"
    : >"$err_file"

    if run_sweep; then
      [[ ! -s "$err_file" ]] || cat -- "$err_file" >&2
      return 0
    else
      exit_code=$?
    fi

    last_stderr="$(awk 'NF { line = $0 } END { print line }' "$err_file")"
    last_stdout_error="$(awk '/^ERROR:/ { line = $0 } END { print line }' "$out_file")"

    if [[ "$last_stderr" == '✖ read ETIMEDOUT' || "$last_stdout_error" == 'ERROR: read ETIMEDOUT' ]]; then
      cat -- "$out_file"
      cat -- "$err_file" >&2
      return "$exit_code"
    fi

    if [[ "$last_stderr" == '✖ busy' || "$last_stdout_error" == 'ERROR: busy' ]]; then
      if (( retry_index < ${#RETRY_DELAYS[@]} )); then
        sleep "${RETRY_DELAYS[$retry_index]}"
        ((retry_index += 1))
        continue
      fi
    fi

    cat -- "$out_file"
    cat -- "$err_file" >&2
    return "$exit_code"
  done
}

main() {
  parse_args "$@"
  validate_max_count
  check_prerequisites
  create_temp_files
  trap cleanup EXIT

  run_with_retries || exit $?

  if ! validate_sweep_result; then
    printf '%s: Oracle returned an invalid sweep result\n' "$COMMAND_NAME" >&2
    cat -- "$out_file" >&2
    exit 1
  fi

  jq -r '.report' "$out_file"
  process_reviews || exit 1
}

main "$@"
