---
name: CI/CD
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
permissions:
  contents: read
jobs:
  dependabot-auto-merge:
    if: >
      github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    uses: dceoy/gha-for-devops/.github/workflows/dependabot-auto-merge.yml@main  # zizmor: ignore[unpinned-uses]
    permissions:
      contents: write
      pull-requests: write
      actions: read
      checks: read
      statuses: read
    with:
      unconditional: true
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
